// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwusbjpwqrfbvvdzsegv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3dXNianB3cXJmYnZ2ZHpzZWd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODYyNzgsImV4cCI6MjA2NTY2MjI3OH0.GkurKH_AgvS_ILPWI1v_tKe-Q335Cq2-FyeJtoHmcZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);